### ISSUE TITLE
Store extents as a bookmarks

### ISSUE THREAD

**Issue by defiantgoat** [Esri/TilePackageKreator#19]
Be able to save the current extent as a bookmark. This is useful when generating multiple TPKs for the same area and being able to quick to back to a saved extent.

Simple implementation would be to have 1 saved bookmark and a buttons to set and zoom to it, this would be enough for starters.

Later and fancier implementation could enable you to name the bookmarks, and have a panel of book marks that you can select from or remove.

**Comment by defiantgoat** [comment]
Currently, the last extent/path is available to be re-drawn as of version 1.2.6.

**Comment by defiantgoat** [comment]
Available with version 1.2.19 and greater.

**Comment by JohnHasthorpe** [comment]
Tested the creation of bookmarks from rectangle, polygon and path. Zooming worked and bookmarks available across basemap options
All working

Comments:
- When using the ocean basemap - it is not possible to see the bookmark button due to its colour
- Download to GeoJson does not let you specify a filename - not sure what is supposed to happen.

Working on
* Ubuntu Linux 16.04
* Macbook Pro Mac OS 10.11.6
* Surface Book Pro - Windows 10
